// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRK_SDj0dV_wxyV5j__ZBMm8aLUNzHBRA',
    appId: '1:888025550166:android:7baa82a7db953b2bd35af7',
    messagingSenderId: '888025550166',
    projectId: 'falsh-chat-1b9cd',
    storageBucket: 'falsh-chat-1b9cd.appspot.com',
  );

  //  FirebaseOptions(
  //   apiKey: 'AIzaSyB4fkkUx_fkBMPuKImox0ffsRO-UBWXBEw',
  //   appId: '1:49698887781:android:17d9221dc0536fb0c80e8c',
  //   messagingSenderId: '49698887781',
  //   projectId: 'rtser-5bd24',
  //   storageBucket: 'rtser-5bd24.appspot.com',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpJD73SHywIK8KJHsts4G_yYjD9Aw_S6k',
    appId: '1:49698887781:ios:028777ee317dba62c80e8c',
    messagingSenderId: '49698887781',
    projectId: 'rtser-5bd24',
    storageBucket: 'rtser-5bd24.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpJD73SHywIK8KJHsts4G_yYjD9Aw_S6k',
    appId: '1:49698887781:ios:028777ee317dba62c80e8c',
    messagingSenderId: '49698887781',
    projectId: 'rtser-5bd24',
    storageBucket: 'rtser-5bd24.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
